[versions]
loom = "1.17-SNAPSHOT"
fletchingTable = "0.1.0-alpha.22"
ksp = "2.3.11"
kotlin = "2.4.10"

devauth = "1.2.2"
commodore = "1.0.1"
kommand = "1.0.1"

fabric-loader = "0.19.3"
fabric-language-kotlin = "1.13.13+kotlin.2.4.10"

fabric-api-26-1 = "0.155.2+26.1.2"

odin-act-26-1 = "e2cf40d9aa"
odin-prod-26-1 = "pb6t335x"

snowbird-26-1 = "016+26.1"

firmament-26-1 = "44.3.0+mc26.1"

lwjgl-nanovg = "3.4.1"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
commodore = { module = "com.github.stivais:Commodore", version.ref = "commodore" }
kommand = { module = "foo.starred:kommand", version.ref = "kommand" }

fabric-api-26-1 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-26-1" }

odin-act-26-1 = { module = "maven.modrinth:odin", version.ref = "odin-act-26-1" }
odin-prod-26-1 = { module = "maven.modrinth:odin", version.ref = "odin-prod-26-1" }

firmament-26-1 = { module = "maven.modrinth:firmament", version.ref = "firmament-26-1" }

snowbird-26-1 = { module = "foo.starred:snowbird", version.ref = "snowbird-26-1" }

lwjgl-nanovg = { module = "org.lwjgl:lwjgl-nanovg", version.ref = "lwjgl-nanovg" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom-obf = { id = "fabric-loom", version.ref = "loom" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
fletchingTable = { id = "dev.kikugie.fletching-table.fabric", version.ref = "fletchingTable" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
