name: Commit Notification
on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        env:
          NOTIFY_TOKEN: ${{ secrets.NOTIFY_TOKEN }}
          COMMITS: ${{ toJson(github.event.commits) }}
          REPO: ${{ github.repository }}
        run: |
          jq -n \
            --arg repo "$REPO" \
            --argjson commits "$COMMITS" \
            '{repo: $repo, commits: $commits}' \
          | curl -X POST "https://builds.aerii.xyz/notify?type=commit" \
            -H "Content-Type: application/json" \
            -H "Authorization: $NOTIFY_TOKEN" \
            -d @-
